### ISSUE TITLE
First use of any genereerIdentificatie action fails due to missing last used identifier

### ISSUE THREAD

**Issue by MLenterman** [wearefrank/zaakbrug#108]
Possible solution would be to set the initial value in de DatabaseChangelog.xml

**Comment by MLenterman** [comment]
[Pipeline GenereerIdentificatieEmulator and 1 more.zip](https://github.com/ibissource/zaakbrug/files/11688247/Pipeline.GenereerIdentificatieEmulator.and.1.more.zip)

**Comment by MLenterman** [comment]
Relates to #94

**Comment by checkiecheck** [comment]
new release zaakbrug 1.13.9 solves this issue
