### ISSUE TITLE
Document status not getting translated back from ZGW to ZDS during geefZaakdocumentLezen geefLijstZaakdocumenten

### ISSUE THREAD

**Issue by Geert-Jan-DH** [wearefrank/zaakbrug#188]
The incoming message in the zaakBrug is based on StuF ZDS 1.1 with enum:

- `Definitief`
- `Gearchiveerd`
- `In bewerking`
- `Ter vaststelling`

The values expected by ZGW are:

- `definitief`
- `gearchiveerd`
- `in_bewerking`
- `ter_vaststelling`

And the problems are in the details: the use of capitals / underscores.

We'd like zaakBrug as interface between StUF and ZGW to translate this `status`.

Until now we managed to work around this issue, but some new functionality in our source application causes more problems.

**Comment by MLenterman** [comment]
Functionally this is already implemented in the ZaakBrug. ZDS to ZGW translation seems to be working as expected, but I see that the other way around, it is giving back the ZGW values instead of the ZDS values. Should be a simple fix.

**Comment by Geert-Jan-DH** [comment]
The same issue is found in the same API for filed `vertrouwelijkheidAanduiding`
