### ISSUE TITLE
Missing error feedback when no roltype with matching omschrijving is found in AddRolToZgw adapter

### ISSUE THREAD

**Issue by MLenterman** [wearefrank/zaakbrug#206]
The AddRolToZgw adapter is used by multiple soap actions (creeerZaak and updateZaak for sure). The CheckForZgwRolType pipe is already checking if a roltype was found or not and throws an error, but an informative description of the error missing.

#204

**Comment by Geert-Jan-DH** [comment]
Deze is denk ik ook gereed @MLenterman?
