### ISSUE TITLE
Cannot evaluate expression (v.1.13.20)

### ISSUE THREAD

**Issue by Geert-Jan-DH** [wearefrank/zaakbrug#209]
Testing the creation of a zaak, I get:

![image](https://github.com/wearefrank/zaakbrug/assets/129515205/63732971-f88d-4c67-88a6-4dfb8bffe7fa)
[Pipeline SoapEndpointRouter_OntvangAsynchroon (1).zip](https://github.com/wearefrank/zaakbrug/files/13476897/Pipeline.SoapEndpointRouter_OntvangAsynchroon.1.zip)

```
<pipe className="nl.nn.adapterframework.pipes.XmlIf" name="CheckForGetZgwAndereZaakResult" 
                                xpathExpression="string-length(ZgwZaak) &gt; 0">
	<forward name="then" path="CallPatchAndereZaak"/>
	<forward name="else" path="EXIT"/>
</pipe>
```

I guess `CallPatchAndereZaak` cannot be found...?

**Comment by checkiecheck** [comment]
Er wordt geprobeerd een zaak te relateren die niet in Open Zaak bestaat. Dit is waarschijnlijk een test situatie van een vorige zaak die niet juist of helemaal niet aangemaakt is geweest in openzaak.

**Comment by Geert-Jan-DH** [comment]
oké, dan laten we deze maar even negeren. Wel vreemd ergens. mIsschien is met die zaak eerder wat fout gegaan.
