### ISSUE TITLE
Error updateZaak_Lk01: gerelateerde zonder persoon (v1.13.20)

### ISSUE THREAD

**Issue by Geert-Jan-DH** [wearefrank/zaakbrug#210]
updateZaak_Lk01 geeft een foutmelding op een rol. Geen idee wat voor rol we missen

[Pipeline SoapEndpointRouter_OntvangAsynchroon.zip](https://github.com/wearefrank/zaakbrug/files/13485505/Pipeline.SoapEndpointRouter_OntvangAsynchroon.zip)

**Comment by Geert-Jan-DH** [comment]
nog een voorbeeld van deze fout (denk ik).

[Pipeline SoapEndpointRouter_OntvangAsynchroon (1).zip](https://github.com/wearefrank/zaakbrug/files/13485843/Pipeline.SoapEndpointRouter_OntvangAsynchroon.1.zip)

**Comment by checkiecheck** [comment]
Het gaat hier om een gerelateerde zonder persoon, maar alleen een adres. Daar is nog geen duidelijke plaatsing in openzaak voor gedefinieerd. Is een uitbreiding van scenarios dat we moeten definieren.
