### ISSUE TITLE
Server memory usage PROD

### ISSUE THREAD

**Issue by Geert-Jan-DH** [wearefrank/zaakbrug#236]
We're a little worried about the continuing increase of memory usage... (v.1.13.24)

PROD for today (900 actions):

![image](https://github.com/wearefrank/zaakbrug/assets/129515205/1f14dc8c-1aa5-41fe-b92a-89bec9eba7e5)

Every max results in a restart.

And the usage of the server is increasing every day.

**Comment by Geert-Jan-DH** [comment]
The evening we'll increase the memory to 6 GB.

**Comment by checkiecheck** [comment]
suggest to decrease the maximum heap to 75 or 70%, with that the garbage collector will be used better.

**Comment by checkiecheck** [comment]
Since newer versions are deployed with better memory management, this issue is resolved?
