### ISSUE TITLE
ZGW API timeout property not present in Helm chart values and chart schema

### ISSUE THREAD

**Issue by MLenterman** [wearefrank/zaakbrug#246]
Its already implemented in the configmap, but not present in values.yaml and chart schema.

![image](https://github.com/wearefrank/zaakbrug/assets/9280762/bd3613ea-09e9-4b98-b4e3-e52c2ed4957e)

**Comment by philipsens** [comment]
Done in https://github.com/wearefrank/charts/releases/tag/zaakbrug-2.1.0
