### ISSUE TITLE
Ladybug shows "Uncaught exception" for "identificatie-niet-uniek"

### ISSUE THREAD

**Issue by Geert-Jan-DH** [wearefrank/zaakbrug#258]
Ladybug shows "Uncaught exception" for "identificatie-niet-uniek"

The pipe PostZgwZaak returns in a creeerZaak:

`{"type":"https://openzaak-zgw.denhaag.nl/ref/fouten/ValidationError/","
code":"invalid",
"title":"Invalid input.",
"status":400,"detail":"",
"instance":"urn:uuid:e0464632-291c-4480-ac02-62ef5c24a0f6",
"invalidParams":[{"name":"identificatie",
                            "code":"identificatie-niet-uniek",
                            "reason":"Deze identificatie bestaat al voor deze bronorganisatie"}]}`

It would be nice if this mesage can be displayed as Status in Ladybug.

**Comment by MLenterman** [comment]
#249 Should help with this. Currently the identificatie-niet-uniek information is lost due to the higher level error handling  "Uncaught exception" overwriting it. This feature will nest previous errors, so that information is retained

**Comment by MLenterman** [comment]
Resolved by #261

**Comment by MLenterman** [comment]
Resolved by #261
